# Choose Your Own Adventure
# Vivian Liang
# 24 September

# Choose your own adventure story focusing on using variables and branching/condiitionals
import time

#Ask the user's name
user_name = input("Hi, welcome to Choose Your Own Adventure, before the game starts, please enter you name!")
print(f"It's nice to meet you {user_name}. Let's begin.")
time.sleep(3)
print("You wake up in a dusty room inside a haunted mansion.")
time.sleep(3)
print("The windows are barred, the air is cold, and you hear footsteps in the distance...")
time.sleep(3)
print("Looking around, you see three possible ways out:")
time.sleep(3)
print("A heavy wooden door,  a creaky stairs leading up, and a cracked window.")
time.sleep(3)
choice_one = input("Do you want to go to the 'door', 'stairs', or 'window': ")
time.sleep(3)

if choice_one == "door":
    print("You slowly approach the wooden door. The handle is rusty and stiff.")
    time.sleep(3)
    print("It’s locked, but you might be able to get out if you try something...")
    time.sleep(3)
    print("Do you want to try to 'pick' the lock quietly, or 'kick' it down with force?")
    time.sleep(3)
    choice_two = input("Type 'pick' or 'kick': ")
    time.sleep(3)
    if choice_two == "pick":
        print("You kneel down with paper clip you found earlier in the room.")
        time.sleep(3)
        print("After a few seconds, you hear a soft *click*... The door opens.")
        time.sleep(3)
        print("But right outside stands a tall guard with glowing red eyes!")
        time.sleep(3)
        print("Do you want to hide in the shadows or try to fight him?")
        time.sleep(3)
        choice_three = input("Type 'hide' or 'fight': ")
        time.sleep(3)
        if choice_three == "hide":
            print("You slip into the shadows as the guard stomps past, unaware of you.")
            time.sleep(3)
            print("Once the path is clear, you slip outside and breathe the fresh air.")
            time.sleep(3)
            print("Congratulations! You have escaped the haunted mansion! You win!😎")
            time.sleep(3)
        elif choice_three == "fight":
            print("You grab a broken chair leg and swing wildly toward the guard.")
            time.sleep(3)
            print("But the guard is too strong. He knocks you down easily.")
            time.sleep(3)
            print("☠️You are captured by the guard!  Game Over.")
            time.sleep(3)
        else:
            print("Not a valid choice. Game Over.")
            time.sleep(3)
    elif choice_two == "kick":
        print("You slam your foot into the door. It bursts open with a loud *CRACK!*")
        time.sleep(3)
        print("The noise echoes through the halls... footsteps are running toward you.")
        time.sleep(3)
        print("Before you can escape, several guards surround you.")
        time.sleep(3)
        print("☠️You are captured by the guards! Game Over.")
        time.sleep(3)
    else:
        print("Not a valid choice. Game Over.")
elif choice_one == "stairs":
    print("The stairs creak under your weight as you climb to the second floor.")
    time.sleep(3)
    print("Dusty portraits glare at you from the walls, and a chill runs down your spine.")
    time.sleep(3)
    print("You find yourself in an old library with shelves towering above you.")
    time.sleep(3)
    print("Behind one painting, you spot a hidden passage, and in the corner stands a tall bookshelf.")
    time.sleep(3)
    choice_two = input("Type 'passage' or 'bookshelf': ")
    time.sleep(3)
    if choice_two == "passage":
        print("You push the painting aside and squeeze into the hidden passage.")
        time.sleep(3)
        print("It’s pitch black and smells of damp earth.")
        time.sleep(3)
        print("You notice a rusty torch on the wall. Do you take it or ignore it?")
        time.sleep(3)
        choice_three = input("Type 'torch' or 'ignore': ")
        time.sleep(3)
        if choice_three == "torch":
            print("You grab the torch and light it. The tunnel glows with a faint orange light.")
            time.sleep(3)
            print("Following the passage, you find a wooden trapdoor leading outside.")
            time.sleep(3)
            print(" You crawl out into the night and escape! You win! ✨")
            time.sleep(3)
        elif choice_three == "ignore":
            print("You step into the darkness without a light.")
            time.sleep(3)
            print("A sudden drop in the floor sends you tumbling into a pit.")
            time.sleep(3)
            print("☠️You are lost forever in the darkness. Game Over.")
            time.sleep(3)
        else:
            print("Not a valid choice. Game Over.")
    elif choice_two == "bookshelf":
        print("You tug at the heavy bookshelf, hoping to find a secret behind it.")
        time.sleep(3)
        print("But it tips forward with a loud crash and pins you underneath.")
        time.sleep(3)
        print("☠️You are trapped forever in the library. Game Over.")
        time.sleep(3)
    else:
        print("Not a valid choice. Game Over.")
elif choice_one == "window":
    print("You try to open the cracked window. Cold air rushes in.")
    time.sleep(3)
    print("Looking down, you see the ground far below. It’s a dangerous height.")
    time.sleep(3)
    print("Do you want to jump down, or carefully climb down the vines?")
    time.sleep(3)
    choice_two = input("Type 'jump' or 'climb': ")
    time.sleep(3)
    if choice_two == "jump":
        print("You leap into the night air, hoping you could make it.")
        time.sleep(3)
        print("But the height is way too high. You hit the ground hard with your leg broken and cannot move.")
        time.sleep(3)
        print("☠️Your escape attempt has failed. Game Over.")
        time.sleep(3)
    elif choice_two == "climb":
        print("You carefully grip the vines growing on the mansion wall.")
        time.sleep(3)
        print("Step by step, you make it down into the  garden below.")
        time.sleep(3)
        print("But you hear barking... guard dogs are nearby!")
        time.sleep(3)
        print("Do you want to try to run for the gates or hide in the bushes nearby?")
        time.sleep(3)
        choice_three = input("Type 'run' or 'hide': ")
        time.sleep(3)
        if choice_three == "run":
            print("You sprint as fast as you can. The dogs chase you, but you reach the gate first.")
            time.sleep(3)
            print("With one last push, you slip outside and slam the gate shut behind you.")
            time.sleep(3)
            print("Congrats! You’ve escaped the haunted mansion! You win!🏆 ")
            time.sleep(3)
        elif choice_three == "hide":
            print("You crouch behind the bushes, holding your breath.")
            time.sleep(3)
            print("The dogs sniff the air, then pounce right at you.")
            time.sleep(3)
            print("☠️The guards hear the noise. You are captured by the guards. Game Over.")
            time.sleep(3)
        else:
            print("Not a valid choice. Game Over.")
            time.sleep(3)
